/// <reference types="node" />
/**
 * @module cli/commands/create-app
 * @audience installer
 * @layer cli
 * @stability stable
 *
 * `spine-framework create-app <slug>` — scaffold a new custom app.
 *
 * Creates the full directory structure under `custom/apps/{slug}/`:
 *   - manifest.json     (app metadata, roles, routes, nav_items)
 *   - index.tsx         (React entry point)
 *   - components/       (empty dir with .gitkeep)
 *
 * **Usage:**
 * ```bash
 * npm run spine-framework create-app my-app
 * npm run spine-framework create-app my-app --name "My App" --role member
 * npm run spine-framework create-app my-app --force
 * ```
 */

import type { Command } from 'commander'
import { existsSync, mkdirSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { adminDb } from '../../functions/_shared/index.ts'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const PROJECT_ROOT = resolve(__dirname, '../../../')

function toTitleCase(slug: string): string {
  return slug.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(' ')
}

function generateManifest(slug: string, name: string, role: string): string {
  return JSON.stringify({
    name,
    slug,
    description: `${name} app`,
    version: "1.0.0",
    required_roles: [role],
    routes: [
      `/${slug}`,
      `/${slug}/dashboard`
    ],
    nav_items: [
      {
        title: "Dashboard",
        path: `/${slug}/dashboard`,
        icon: "LayoutDashboard",
        order: 1
      }
    ],
    features: [],
    dependencies: [],
    entry_point: "./index.tsx"
  }, null, 2) + '\n'
}

function generateIndexTsx(slug: string, name: string): string {
  const componentName = slug.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('')
  return `/**
 * @module custom/apps/${slug}
 * @audience custom
 * @layer frontend-app
 * @stability experimental
 *
 * Entry point for the ${name} app.
 * Generated by spine-framework CLI on ${new Date().toISOString().split('T')[0]}.
 */

import * as React from 'react'
import { Routes, Route, Navigate } from 'react-router-dom'

function ${componentName}Dashboard() {
  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-2">${name}</h1>
      <p className="text-slate-500">Welcome to ${name}. Edit custom/apps/${slug}/index.tsx to get started.</p>
    </div>
  )
}

export default function ${componentName}App() {
  return (
    <Routes>
      <Route path="/" element={<Navigate to="dashboard" replace />} />
      <Route path="dashboard" element={<${componentName}Dashboard />} />
    </Routes>
  )
}
`
}

async function createApp(slug: string, options: { name?: string; role: string; force: boolean }): Promise<void> {
  const name = options.name || toTitleCase(slug)
  const appDir = resolve(PROJECT_ROOT, `custom/apps/${slug}`)

  console.log(`\n🔧 Creating app '${slug}'...`)

  if (existsSync(appDir) && !options.force) {
    console.error(`  ❌ App directory already exists: custom/apps/${slug}`)
    console.error(`     Use --force to overwrite`)
    process.exit(1)
  }

  // 1. Create directories
  mkdirSync(resolve(appDir, 'components'), { recursive: true })
  console.log(`  ✓ Created custom/apps/${slug}/`)
  console.log(`  ✓ Created custom/apps/${slug}/components/`)

  // 2. manifest.json
  writeFileSync(
    resolve(appDir, 'manifest.json'),
    generateManifest(slug, name, options.role)
  )
  console.log(`  ✓ Created custom/apps/${slug}/manifest.json`)

  // 3. index.tsx
  writeFileSync(
    resolve(appDir, 'index.tsx'),
    generateIndexTsx(slug, name)
  )
  console.log(`  ✓ Created custom/apps/${slug}/index.tsx`)

  // 4. components/.gitkeep
  writeFileSync(resolve(appDir, 'components', '.gitkeep'), '')

  // 5. Insert app record into database
  console.log(`  Registering app in database...`)
  const { data: existing } = await adminDb
    .from('apps')
    .select('id')
    .eq('slug', slug)
    .single()

  if (existing) {
    console.log(`  ⚠️  App '${slug}' already exists in database (skipping insert)`)
  } else {
    const { error: insertErr } = await adminDb
      .from('apps')
      .insert({
        slug,
        name,
        route_prefix: `/${slug}`,
        renderer: 'custom',
        is_active: true,
        is_system: false,
        min_role: options.role,
      })

    if (insertErr) {
      console.error(`  ❌ Database insert failed: ${insertErr.message}`)
      console.error(`     Run manually: INSERT INTO apps (slug, name, route_prefix, renderer, is_active)`)
      console.error(`     VALUES ('${slug}', '${name}', '/${slug}', 'custom', true);`)
    } else {
      console.log(`  ✓ App registered in database`)
    }
  }

  console.log(`\n✅ App '${name}' ready at custom/apps/${slug}/`)
  console.log(`\n   Next steps:`)
  console.log(`   1. Edit custom/apps/${slug}/manifest.json to configure routes and nav`)
  console.log(`   2. Edit custom/apps/${slug}/index.tsx to build your app`)
  console.log(`   3. npm run assemble && netlify dev`)
}

export function registerCreateAppCommands(program: Command) {
  program
    .command('create-app <slug>')
    .description('Scaffold a new custom app in custom/apps/{slug}/')
    .option('--name <name>', 'Display name for the app (defaults to title-cased slug)')
    .option('--role <role>', 'Required role to access this app', 'member')
    .option('--force', 'Overwrite existing files', false)
    .action(async (slug, opts) => {
      try {
        await createApp(slug, opts)
      } catch (err: any) {
        console.error('Error:', err.message)
        process.exit(1)
      }
    })
}
