/// <reference types="node" />
/**
 * @module cli/commands/generate
 * @audience installer
 * @layer cli
 * @stability stable
 *
 * `spine generate` command — code scaffolding for extending Spine safely.
 * Generates type definitions, handlers, and UI pages in v2-custom/ only.
 *
 * **Commands:**
 * | Subcommand              | Description                                           |
 * |-------------------------|-------------------------------------------------------|
 * | `generate type <slug>`  | Create new type with handler and UI stubs             |
 * | `generate function <name>` | Create new Netlify function stub                   |
 *
 * **What gets generated for `type`:**
 * 1. Type record in database (item type by default)
 * 2. Handler stub: `v2-custom/functions/{slug}.ts`
 * 3. UI page stub: `v2-custom/src/pages/{slug}/index.tsx`
 *
 * **What gets generated for `function`:**
 * 1. Netlify function stub: `v2-custom/functions/{name}.ts`
 * 2. Basic handler structure with middleware imports
 *
 * **Usage:**
 * ```bash
 * spine generate type ticket-v2
 * spine generate function webhook-handler
 * ```
 *
 * @seeAlso functions/types.ts (type CRUD API)
 * @seeAlso functions/_shared/middleware.ts (handler structure)
 */

import type { Command } from 'commander'
import { buildCliContext, handleError } from '../context.ts'
import { adminDb } from '../../functions/_shared/index.ts'
import { existsSync, mkdirSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const PROJECT_ROOT = resolve(__dirname, '../../../')

// ─── TYPE GENERATION ─────────────────────────────────────────────────────────

async function generateType(ctx: any, slug: string, options: any): Promise<void> {
  const name = options.name || slug.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(' ')
  const kind = options.kind || 'item'
  const description = options.description || `${name} type generated by spine CLI`

  console.log(`\n🔧 Generating type '${slug}'...`)

  // Step 1: Create type record in database
  console.log('  Step 1: Creating type record in database...')

  const { data: existing, error: checkErr } = await adminDb
    .from('types')
    .select('id')
    .eq('slug', slug)
    .eq('kind', kind)
    .single()

  if (checkErr && checkErr.code !== 'PGRST116') { // PGRST116 = not found
    throw new Error(`Failed to check existing type: ${checkErr.message}`)
  }

  if (existing) {
    console.log(`  ⚠️  Type '${slug}' already exists (skipping DB creation)`)
  } else {
    const designSchema = {
      fields: {
        title: {
          type: 'string',
          required: true,
          label: 'Title',
          description: `Title for this ${name}`
        },
        status: {
          type: 'select',
          options: ['open', 'in_progress', 'closed'],
          default: 'open',
          label: 'Status'
        }
      },
      layout: {
        detail: ['title', 'status'],
        list: ['title', 'status']
      }
    }

    const { error: insertErr } = await adminDb
      .from('types')
      .insert({
        kind,
        slug,
        name,
        description,
        design_schema: designSchema,
        validation_schema: {},
        ownership: 'system',
        is_active: true
      })

    if (insertErr) {
      throw new Error(`Failed to create type: ${insertErr.message}`)
    }

    console.log('  ✓ Type record created')
  }

  // Step 2: Generate handler stub
  console.log('  Step 2: Generating handler stub...')
  const handlerPath = resolve(PROJECT_ROOT, `v2-custom/functions/${slug}.ts`)

  if (existsSync(handlerPath) && !options.force) {
    console.log(`  ⚠️  Handler stub already exists: ${handlerPath}`)
  } else {
    const handlerCode = generateHandlerStub(slug, kind, name)
    writeFileSync(handlerPath, handlerCode)
    console.log(`  ✓ Handler stub created: v2-custom/functions/${slug}.ts`)
  }

  // Step 3: Generate UI page stub
  console.log('  Step 3: Generating UI page stub...')
  const pageDir = resolve(PROJECT_ROOT, `v2-custom/src/pages/${slug}`)
  const pagePath = resolve(pageDir, 'index.tsx')

  if (existsSync(pagePath) && !options.force) {
    console.log(`  ⚠️  UI page stub already exists: ${pagePath}`)
  } else {
    mkdirSync(pageDir, { recursive: true })
    const pageCode = generatePageStub(slug, name, kind)
    writeFileSync(pagePath, pageCode)
    console.log(`  ✓ UI page stub created: v2-custom/src/pages/${slug}/index.tsx`)
  }

  console.log(`\n✅ Type '${slug}' generation complete!`)
  console.log(`   Next steps:`)
  console.log(`   1. Edit v2-custom/functions/${slug}.ts to implement custom logic`)
  console.log(`   2. Edit v2-custom/src/pages/${slug}/index.tsx to customize the UI`)
  console.log(`   3. Run 'spine dev' to see your changes`)
}

function generateHandlerStub(slug: string, kind: string, name: string): string {
  return `/**
 * @module ${slug}
 * @audience custom
 * @layer api-handler
 * @stability experimental
 *
 * Custom handler for ${name} (${kind} type).
 * Generated by spine CLI on ${new Date().toISOString()}.
 *
 * Extend this handler to add custom logic for your type.
 */

import { createHandler } from '../v2-core/functions/_shared/middleware'

export const handler = createHandler(async (ctx) => {
  const method = ctx.query?.method || 'GET'

  switch (method) {
    case 'GET':
      // TODO: Implement GET logic
      return { message: '${name} handler - GET not implemented' }

    case 'POST':
      // TODO: Implement POST logic
      return { message: '${name} handler - POST not implemented' }

    case 'PATCH':
      // TODO: Implement PATCH logic
      return { message: '${name} handler - PATCH not implemented' }

    case 'DELETE':
      // TODO: Implement DELETE logic
      return { message: '${name} handler - DELETE not implemented' }

    default:
      throw new Error('Unsupported method: ' + method)
  }
})
`
}

function generatePageStub(slug: string, name: string, kind: string): string {
  return `/**
 * @page ${slug}/index
 * @audience custom
 * @layer page
 * @stability experimental
 *
 * UI page for ${name} (${kind} type).
 * Generated by spine CLI on ${new Date().toISOString()}.
 */

import React from 'react'
import { useParams } from 'react-router-dom'
import { useApi } from '../../v2-core/src/hooks/useApi'
import { apiFetch } from '../../v2-core/src/lib/api'

export default function ${name.replace(/\s+/g, '')}Page() {
  const { id } = useParams()

  const { data, loading, error } = useApi(
    () => apiFetch('/.netlify/functions/${slug}' + (id ? '?id=' + id : '')),
    { immediate: true }
  )

  if (loading) return <div>Loading...</div>
  if (error) return <div>Error: {error.message}</div>

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-4">${name}</h1>
      <pre className="bg-gray-100 p-4 rounded">
        {JSON.stringify(data, null, 2)}
      </pre>
      <p className="mt-4 text-gray-600">
        Edit v2-custom/src/pages/${slug}/index.tsx to customize this page.
      </p>
    </div>
  )
}
`
}

// ─── FUNCTION GENERATION ─────────────────────────────────────────────────────

async function generateFunction(name: string, options: any): Promise<void> {
  console.log(`\n🔧 Generating function '${name}'...`)

  const handlerPath = resolve(PROJECT_ROOT, `v2-custom/functions/${name}.ts`)

  if (existsSync(handlerPath) && !options.force) {
    console.log(`  ⚠️  Function already exists: ${handlerPath}`)
    console.log(`  Use --force to overwrite`)
    return
  }

  const handlerCode = generateFunctionStub(name, options.description)
  writeFileSync(handlerPath, handlerCode)

  console.log(`✅ Function '${name}' created!`)
  console.log(`   Location: v2-custom/functions/${name}.ts`)
  console.log(`   Next steps:`)
  console.log(`   1. Edit the handler to implement your logic`)
  console.log(`   2. Run 'spine dev' to see your changes`)
}

function generateFunctionStub(name: string, description?: string): string {
  return `/**
 * @module ${name}
 * @audience custom
 * @layer api-handler
 * @stability experimental
 *
 * ${description || `Custom Netlify function: ${name}`}
 * Generated by spine CLI on ${new Date().toISOString()}.
 */

import { createHandler } from '../v2-core/functions/_shared/middleware'

export const handler = createHandler(async (ctx) => {
  // Access principal: ctx.principal (human, machine, or system)
  // Access database: ctx.db (RLS-scoped) or import { adminDb } for admin access
  // Access query params: ctx.query

  const q = ctx.query || {}
  const action = q.action || 'default'

  switch (action) {
    case 'default':
      return {
        message: 'Hello from ${name}',
        principal: ctx.principal?.id,
        timestamp: new Date().toISOString()
      }

    // TODO: Add more actions here
    // case 'custom':
    //   return { data: await yourCustomLogic(ctx) }

    default:
      return {
        error: 'Unknown action: ' + action,
        available_actions: ['default']
      }
  }
})
`
}

// ─── COMMAND REGISTRATION ────────────────────────────────────────────────────

export function registerGenerateCommands(program: Command) {
  const generate = program
    .command('generate')
    .description('Generate code stubs for extending Spine')

  generate
    .command('type <slug>')
    .description('Generate a new type with handler and UI stubs')
    .option('--name <name>', 'Display name for the type')
    .option('--kind <kind>', 'Type kind (item, account, person)', 'item')
    .option('--description <desc>', 'Type description')
    .option('--force', 'Overwrite existing files', false)
    .action(async (slug, opts) => {
      try {
        const ctx = await buildCliContext()
        await generateType(ctx, slug, opts)
      } catch (err: any) {
        handleError(err)
      }
    })

  generate
    .command('function <name>')
    .description('Generate a new Netlify function stub')
    .option('--description <desc>', 'Function description')
    .option('--force', 'Overwrite existing file', false)
    .action(async (name, opts) => {
      try {
        await generateFunction(name, opts)
      } catch (err: any) {
        handleError(err)
      }
    })
}
